---
deployment:
  tasks:
    - export DEPLOYPATH=/home/uwfuzcig/public_html/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp about.php $DEPLOYPATH
    - /bin/cp service.php $DEPLOYPATH
    - /bin/cp contact.php $DEPLOYPATH
    - /bin/cp sendemail.php $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
